### ISSUE TITLE
请教require下面的方法为何不会被覆盖

### ISSUE THREAD

**Issue by fz6m** [theanarkh/Node.js-Function-Wrapper#1]
有一个问题想向大佬请教，这里把原来的 `require` 复写了，但是 `require` 本身不光光具有函数调用，他自身还可以调用 `require.resolve`，`require.cache` 等属性或者方法，按理说 new require 这个函数没有这些方法或者属性的。

```js
const originRequire = Module.prototype.require;

function newRequire(...args){
    let exports = originRequire.call(this, ...args);
    // 略
    return exports;
}

Module.prototype.require = newRequire;

// 仍然可以调用
require.cache // object
require.resolve // function
```

但是实测了一下，貌似这些属性和方法没有被破坏，是为什么呢？

**Comment by theanarkh** [comment]
> 



> 有一个问题想向大佬请教，这里把原来的 `require` 复写了，但是 `require` 本身不光光具有函数调用，他自身还可以调用 `require.resolve`，`require.cache` 等属性或者方法，按理说 new require 这个函数没有这些方法或者属性的。
> 
> ```js
> const originRequire = Module.prototype.require;
> 
> function newRequire(...args){
>     let exports = originRequire.call(this, ...args);
>     // 略
>     return exports;
> }
> 
> Module.prototype.require = newRequire;
> 
> // 仍然可以调用
> require.cache // object
> require.resolve // function
> ```
> 
> 但是实测了一下，貌似这些属性和方法没有被破坏，是为什么呢？

因为 Module.prototype.require，不是业务代码里使用的那个 require。业务里面那个是 Module.prototype.require 的壳。
```
// 业务里使用的 require
require = function require(path) {
      // Module.prototype.require
      return mod.require(path);
};
require.resolve = resolve;
require.cache = Module._cache;
```

**Comment by fz6m** [comment]
> > 
> 
> > 有一个问题想向大佬请教，这里把原来的 `require` 复写了，但是 `require` 本身不光光具有函数调用，他自身还可以调用 `require.resolve`，`require.cache` 等属性或者方法，按理说 new require 这个函数没有这些方法或者属性的。
> > ```js
> > const originRequire = Module.prototype.require;
> > 
> > function newRequire(...args){
> >     let exports = originRequire.call(this, ...args);
> >     // 略
> >     return exports;
> > }
> > 
> > Module.prototype.require = newRequire;
> > 
> > // 仍然可以调用
> > require.cache // object
> > require.resolve // function
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是实测了一下，貌似这些属性和方法没有被破坏，是为什么呢？
> 
> 因为 Module.prototype.require，不是业务代码里使用的那个 require。业务里面那个是 Module.prototype.require 的壳。
> 
> ```
> // 业务里使用的 require
> require = function require(path) {
>       // Module.prototype.require
>       return mod.require(path);
> };
> require.resolve = resolve;
> require.cache = Module._cache;
> ```

感谢大佬解答！

（我还发现一种解法，看起来只拦截了调用，心智压力更小：

```js
Module.prototype.require = new Proxy(Module.prototype.require, {
    apply(target, thisArg, argumentsList){

        // do any...

        return Reflect.apply(target, thisArg, argumentsList)
    }
})
```
